# Generated by Django 3.2.6 on 2021-12-11 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer', models.TextField(blank=True, null=True)),
                ('upVotes', models.IntegerField(blank=True, default=0, null=True)),
                ('downVotes', models.IntegerField(blank=True, default=0, null=True)),
                ('numComments', models.IntegerField(blank=True, default=0, null=True)),
                ('answeredAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('askedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment', models.TextField(blank=True, null=True)),
                ('commentAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('useranswer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionandanswer.answer')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='userquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionandanswer.question'),
        ),
    ]
