# Generated by Django 3.2.6 on 2021-12-22 14:41

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0002_answer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='userquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.CharField, to='questionandanswer.question'),
        ),
    ]
