# Generated by Django 3.2.6 on 2021-12-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0004_alter_answer_userquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='slug',
        ),
    ]
