# Generated by Django 3.2.6 on 2021-12-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0008_auto_20211224_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downvote',
            old_name='downvotes',
            new_name='votes',
        ),
        migrations.RenameField(
            model_name='upvote',
            old_name='upvotes',
            new_name='votes',
        ),
        migrations.AddField(
            model_name='answer',
            name='downVotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='upVotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
