# Generated by Django 3.2.6 on 2021-12-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0010_auto_20211224_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downvote',
            old_name='dvotes',
            new_name='votes',
        ),
        migrations.RenameField(
            model_name='upvote',
            old_name='uvotes',
            new_name='votes',
        ),
    ]
