# Generated by Django 3.2.6 on 2021-12-31 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0012_auto_20211224_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionandanswer.question'),
        ),
        migrations.AddField(
            model_name='downvote',
            name='userquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionandanswer.question'),
        ),
        migrations.AddField(
            model_name='upvote',
            name='userquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionandanswer.question'),
        ),
    ]
