# Generated by Django 3.2.6 on 2021-12-31 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0013_auto_20211231_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='numComments',
            new_name='comments',
        ),
    ]
