# Generated by Django 3.2.6 on 2021-12-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0014_rename_numcomments_answer_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='downVotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='upVotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
