# Generated by Django 3.2.6 on 2022-01-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0016_answer_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='numAnswers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
