# Generated by Django 3.2.6 on 2022-02-01 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionandanswer', '0018_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='userquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionandanswer.question'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='useranswer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionandanswer.answer'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='userquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionandanswer.question'),
        ),
        migrations.AlterField(
            model_name='downvote',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionandanswer.answer'),
        ),
        migrations.AlterField(
            model_name='downvote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='downvote',
            name='userquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionandanswer.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionandanswer.answer'),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='userquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionandanswer.question'),
        ),
    ]
