# Generated by Django 3.2.6 on 2022-02-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0019_auto_20220201_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
