# Generated by Django 3.2.6 on 2022-02-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0020_auto_20220203_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='community/images'),
        ),
        migrations.AlterField(
            model_name='question',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='community/images'),
        ),
    ]
