# Generated by Django 3.2.6 on 2022-02-05 06:28

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0021_auto_20220205_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='community/images', validators=[backend.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='community/images', validators=[backend.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='question',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='community/images', validators=[backend.validators.validate_file_size]),
        ),
    ]
