# Generated by Django 3.2.6 on 2022-02-07 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0022_auto_20220205_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
