# Generated by Django 3.2.6 on 2023-02-03 04:31

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0024_alter_question_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='userImage',
            field=models.ImageField(blank=True, default='static/profile-pic.jpg', null=True, upload_to='images', validators=[backend.validators.validate_file_size]),
        ),
    ]
