# Generated by Django 3.2.6 on 2022-02-05 20:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamber', '0018_auto_20220205_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verifiable',
            fields=[
                ('file', models.FileField(blank=True, null=True, upload_to='verifiables/files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc'])])),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chamber.chamber')),
            ],
        ),
    ]
