# Generated by Django 3.2.6 on 2022-02-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifiables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifiable',
            old_name='uploadedAt',
            new_name='uploadedAT',
        ),
    ]
