# Generated by Django 3.2.6 on 2022-02-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifiables', '0002_rename_uploadedat_verifiable_uploadedat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifiable',
            old_name='uploadedAT',
            new_name='uploadedAt',
        ),
    ]
