# Generated by Django 3.2.6 on 2022-02-05 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifiables', '0004_verifiable_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifiable',
            old_name='member',
            new_name='chamberMember',
        ),
    ]
