# Generated by Django 3.2.6 on 2022-02-09 21:41

import backend.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarkedbook',
            name='bookmarkedAt',
        ),
        migrations.RemoveField(
            model_name='bookmarkedlawyer',
            name='bookmarkedAt',
        ),
        migrations.AddField(
            model_name='bookmarkedbook',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookmarkedbook',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='store/images', validators=[backend.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
        migrations.AddField(
            model_name='bookmarkedbook',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookmarkedlawyer',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookmarkedlawyer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookmarkedlawyer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='chamber/images', validators=[backend.validators.validate_file_size]),
        ),
    ]
