# Generated by Django 3.2.6 on 2023-02-02 20:18

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_useraccount_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile-pic.jpg', null=True, upload_to='images', validators=[backend.validators.validate_file_size]),
        ),
    ]
