# Generated by Django 3.2.6 on 2022-02-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexquirynotifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerNotification',
        ),
    ]
