# Generated by Django 3.2.6 on 2022-02-14 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0023_remove_tag_user'),
        ('lexquirynotifications', '0002_delete_answernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentQuestionNotification',
            fields=[
                ('text', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionandanswer.question')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogNotification',
        ),
    ]
