# Generated by Django 3.2.6 on 2022-03-21 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0024_auto_20220303_1857'),
        ('lexquirynotifications', '0003_auto_20220214_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlanNotifications',
            fields=[
                ('text', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chamber.chamber')),
            ],
        ),
    ]
