# Generated by Django 3.2.6 on 2022-03-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0024_auto_20220303_1857'),
        ('lexquirynotifications', '0004_paymentplannotifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentPlanNotifications',
            new_name='PaymentPlanNotification',
        ),
    ]
