# Generated by Django 3.2.6 on 2022-04-21 16:42

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexquirynotifications', '0006_paymentplannotification_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyernotification',
            name='notificationImage',
            field=models.ImageField(blank=True, null=True, upload_to='notification/images', validators=[backend.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='questionnotification',
            name='notificationImage',
            field=models.ImageField(blank=True, null=True, upload_to='notification/images', validators=[backend.validators.validate_file_size]),
        ),
    ]
