# Generated by Django 3.2.6 on 2022-05-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexquirynotifications', '0010_alter_recentquestionnotification_notificationimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyernotification',
            name='notificationImage',
        ),
        migrations.RemoveField(
            model_name='recentquestionnotification',
            name='notificationImage',
        ),
    ]
