# Generated by Django 3.2.6 on 2022-02-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
