# Generated by Django 3.2.6 on 2022-02-10 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_alter_subscriber_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
