# Generated by Django 3.2.6 on 2022-01-08 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawbook',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='lawbook',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc'])]),
        ),
    ]
