# Generated by Django 3.2.6 on 2022-01-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawbooks', '0002_auto_20220108_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawbook',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lawbook',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
