# Generated by Django 3.2.6 on 2022-01-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawbooks', '0003_auto_20220108_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawbook',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
