# Generated by Django 3.2.6 on 2022-01-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawbooks', '0006_auto_20220125_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawbook',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
