# Generated by Django 3.2.6 on 2022-02-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawbooks', '0008_auto_20220201_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawbook',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='store/images'),
        ),
        migrations.AlterField(
            model_name='lawbook',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='store/books'),
        ),
    ]
