# Generated by Django 3.2.6 on 2022-02-05 06:28

import backend.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawbooks', '0009_auto_20220205_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawbook',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='store/images', validators=[backend.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='lawbook',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='store/books', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf, doc'])]),
        ),
    ]
