# Generated by Django 3.2.6 on 2022-02-07 14:57

import backend.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawbooks', '0010_auto_20220205_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawbook',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='store/images', validators=[backend.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg, png'])]),
        ),
    ]
