# Generated by Django 3.2.6 on 2022-02-09 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawbooks', '0012_auto_20220207_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawbook',
            name='isBookmarked',
        ),
    ]
