# Generated by Django 3.2.6 on 2021-12-26 15:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0006_auto_20211226_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryNames',
            new_name='CategoryName',
        ),
    ]
