# Generated by Django 3.2.6 on 2021-12-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_rename_categorynames_categoryname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='categoryname',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
