# Generated by Django 3.2.6 on 2022-01-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_auto_20211226_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryname',
            name='user',
        ),
        migrations.RemoveField(
            model_name='categoryname',
            name='userCategory',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryName',
        ),
    ]
