# Generated by Django 3.2.6 on 2022-02-07 00:46

import backend.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_alter_categoryname_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='categoryname',
            name='user',
        ),
        migrations.AlterField(
            model_name='categoryname',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/images', validators=[backend.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
