# Generated by Django 3.2.6 on 2022-01-20 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(blank=True, max_length=200, null=True)),
                ('is_lawfirm', models.BooleanField(default=False)),
                ('is_lawyer', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('topLawyerOfTheMonth', models.BooleanField(default=False)),
                ('communityAccess', models.BooleanField(default=False)),
                ('messagingAccess', models.BooleanField(default=False)),
                ('numReviews', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('degree', models.CharField(blank=True, max_length=300, null=True)),
                ('educationInstitution', models.CharField(blank=True, max_length=300, null=True)),
                ('educationDate', models.CharField(blank=True, max_length=200, null=True)),
                ('membershipInstitution', models.CharField(blank=True, max_length=300, null=True)),
                ('membershipPosition', models.CharField(blank=True, max_length=200, null=True)),
                ('membershipDate', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamber.chamber')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('area', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamber.chamber')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamber.chamber')),
            ],
        ),
    ]
