# Generated by Django 3.2.6 on 2022-01-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0002_practicearea_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
