# Generated by Django 3.2.6 on 2022-01-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0004_auto_20220121_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='practicearea',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
