# Generated by Django 3.2.6 on 2022-01-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0008_auto_20220122_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
