# Generated by Django 3.2.6 on 2022-01-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0010_rename_lawyerreview_memberreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
