# Generated by Django 3.2.6 on 2022-01-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0011_chamber_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamber',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
