# Generated by Django 3.2.6 on 2022-01-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0012_alter_chamber_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamber',
            old_name='rating',
            new_name='memberRating',
        ),
    ]
