# Generated by Django 3.2.6 on 2022-01-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0013_rename_rating_chamber_memberrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamber',
            name='memberRating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
