# Generated by Django 3.2.6 on 2022-02-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0016_auto_20220201_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamber',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='chamber/images'),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='chamber/images'),
        ),
    ]
