# Generated by Django 3.2.6 on 2022-02-05 06:28

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0017_auto_20220205_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamber',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='chamber/images', validators=[backend.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='chamber/images', validators=[backend.validators.validate_file_size]),
        ),
    ]
