# Generated by Django 3.2.6 on 2022-02-11 19:06

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0018_auto_20220205_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamber',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile-pic.jpg', null=True, upload_to='chamber/images', validators=[backend.validators.validate_file_size]),
        ),
    ]
