# Generated by Django 3.2.6 on 2022-02-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0019_alter_chamber_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
