# Generated by Django 3.2.6 on 2022-02-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0021_remove_chamber_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
