# Generated by Django 3.2.6 on 2022-03-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0022_chamber_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='elite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chamber',
            name='lexquiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chamber',
            name='standard',
            field=models.BooleanField(default=True),
        ),
    ]
