# Generated by Django 3.2.6 on 2022-03-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0023_auto_20220303_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamber',
            old_name='elite',
            new_name='elite_firm',
        ),
        migrations.RenameField(
            model_name='chamber',
            old_name='lexquiry',
            new_name='firm',
        ),
        migrations.RenameField(
            model_name='chamber',
            old_name='standard',
            new_name='free',
        ),
        migrations.AddField(
            model_name='chamber',
            name='lexerati',
            field=models.BooleanField(default=False),
        ),
    ]
