# Generated by Django 3.2.6 on 2022-03-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0025_paymentplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='paidAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
