# Generated by Django 3.2.6 on 2022-04-21 16:42

import backend.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0027_alter_paymentplan_paidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='verifiables/files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc'])]),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='chamber/images', validators=[backend.validators.validate_file_size]),
        ),
    ]
