# Generated by Django 3.2.6 on 2023-02-03 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0030_alter_chamber_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamber',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='verifiables/files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc'])]),
        ),
    ]
